api_key="0337507891msh492c3e9c4683fc2p19f021jsn8671df628f1c"
host = "realtor-com-real-estate.p.rapidapi.com"
url_for_sale = "https://realtor-com-real-estate.p.rapidapi.com/for-sale"
url_for_rent = "https://realtor-com-real-estate.p.rapidapi.com/for-rent"
url_estimate = "https://realtor-com-real-estate.p.rapidapi.com/for-sale/home-estimate-value"